BROKER_TEMPLATE: &BROKER_TEMPLATE
  env:
    TRAVELING_RUBY_INSTALL_PATH: ${HOME}/.pact
    PATH: ${HOME}/.pact:${PATH}
  broker_test_script: |
    curl -fsSL https://raw.githubusercontent.com/YOU54F/traveling-ruby/traveling-pact/cli.sh | sh
    pact-broker-app.sh &
    wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 0.0.0.0:9292 -t 20 -- echo broker is up
    killall ruby || true

broker_macos_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  <<: *BROKER_TEMPLATE
broker_linux_arm_task:
  arm_container:
    image: python:3.11-slim
  deps_script: apt update -y && apt install -y wget curl procps netcat
  <<: *BROKER_TEMPLATE
broker_linux_amd_task:
  container:
    image: python:3.11-slim
  deps_script: apt update -y && apt install -y wget curl procps netcat
  <<: *BROKER_TEMPLATE
broker_linux_arm_alpine_task:
  arm_container:
    image: python:3.11-alpine
  deps_script: apk add wget curl procps gcompat libc6-compat bash
  <<: *BROKER_TEMPLATE
broker_linux_amd_alpine_task:
  container:
    image: python:3.11-alpine
  deps_script: apk add wget curl procps gcompat libc6-compat bash
  <<: *BROKER_TEMPLATE
