name: broker in a box

on:
  push:
    # branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-22.04, 
            ubuntu-22.04-arm, 
            macos-15, 
            macos-15-intel, 
            windows-latest, 
            windows-11-arm
          ]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - id: pact-broker-cli
        uses: you54f/pact-broker-in-a-box@test-cli
      - name: Check broker
        run: |
          curl localhost:9292
          pact broker list-latest-pact-versions -b http://localhost:9292