name: broker in a box

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - run: echo "TRAVELING_RUBY_INSTALL_PATH=${HOME}/.pact" >>$GITHUB_ENV
    - run: echo "PATH=${PATH}:${PWD}/.pact" >>$GITHUB_ENV
    - name: test pb in a box
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/YOU54F/traveling-ruby/traveling-pact/cli.sh | sh -s -- --ci
        pact-broker-app.sh &
        wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 0.0.0.0:9292 -t 20 -- echo broker is up
        killall ruby || true
